---
swagger: "2.0"
info:
  description: MUVE API
  version: 1.0.0
  title: MUVE
host: 127.0.0.1:8000
schemes:
- http
paths:
  /:
    get:
      tags:
      - ""
      description: Open-API Schema
      operationId: list
      parameters: []
      responses:
        "200":
          description: Open-API Schema
  /api/address/:
    get:
      tags:
      - api
      summary: Return a list of all addresses of a user.
      description: Return a list of all addresses of a user.
      operationId: address_list
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        "200":
          description: ""
    post:
      tags:
      - api
      summary: Add a new Address.
      description: Add a new Address.
      operationId: address_create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data'
      responses:
        "201":
          description: ""
  /api/address/{id}/:
    get:
      tags:
      - api
      summary: Return a particular address of a User.
      description: Return a particular address of a User.
      operationId: address_read
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user address.
        required: true
        type: integer
      responses:
        "200":
          description: Return a particular address that matches the ID
    put:
      tags:
      - api
      summary: Update an Address.
      description: Update an Address.
      operationId: address_update
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user address.
        required: true
        type: integer
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_1'
      responses:
        "200":
          description: ""
    delete:
      tags:
      - api
      summary: Delete an Address.
      description: Delete an Address.
      operationId: address_delete
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user address.
        required: true
        type: integer
      responses:
        "204":
          description: ""
    patch:
      tags:
      - api
      summary: Update an Address.
      description: Update an Address.
      operationId: address_partial_update
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user address.
        required: true
        type: integer
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_2'
      responses:
        "200":
          description: ""
  /api/cash_call/:
    get:
      tags:
      - api
      summary: Return a list of all the users withdrawals.
      description: Return a list of all the users withdrawals.
      operationId: cash_call_list
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        "200":
          description: ""
    post:
      tags:
      - api
      summary: Make a new withdrawal.
      description: Make a new withdrawal.
      operationId: cash_call_create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_3'
      responses:
        "201":
          description: ""
  /api/cash_call/{id}/:
    get:
      tags:
      - api
      summary: Return the given withdrawal.
      description: Return the given withdrawal.
      operationId: cash_call_read
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this cash call.
        required: true
        type: integer
      responses:
        "200":
          description: Get details of a particular withdrawal
  /api/refill/:
    get:
      tags:
      - api
      summary: Return a list of all users deposits.
      description: Return a list of all users deposits.
      operationId: refill_list
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        "200":
          description: ""
    post:
      tags:
      - api
      summary: Make a new deposit.
      description: Make a new deposit.
      operationId: refill_create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_4'
      responses:
        "201":
          description: ""
  /api/refill/{id}/:
    get:
      tags:
      - api
      summary: Return the given deposit
      description: Return the given deposit
      operationId: refill_read
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this refill.
        required: true
        type: integer
      responses:
        "200":
          description: Get details of a particular Deposit
  /api/token/:
    post:
      tags:
      - api
      summary: Takes a set of user credentials and returns an access and refresh JSON web
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      operationId: token_create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_5'
      responses:
        "201":
          description: Create token pair to prove the authentication of those credentials.
  /api/token/refresh/:
    post:
      tags:
      - api
      summary: Takes a refresh type JSON web token and returns an access type JSON web
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      operationId: token_refresh_create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_6'
      responses:
        "201":
          description: ""
  /api/user/:
    get:
      tags:
      - api
      summary: Return a list of all Users if Admin User.
      description: Return a list of all Users if Admin User.
      operationId: user_list
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        "200":
          description: ""
  /api/user/{id}/:
    get:
      tags:
      - api
      summary: Return the User matching the Id.
      description: Return the User matching the Id.
      operationId: user_read
      parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user.
        required: true
        type: integer
      responses:
        "200":
          description: ""
  /register/:
    post:
      tags:
      - register
      summary: New User registration Form
      description: New User registration Form
      operationId: create
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        required: false
        schema:
          $ref: '#/definitions/data_7'
      responses:
        "201":
          description: New User Registration
securityDefinitions:
  basic:
    type: basic
definitions:
  data_6:
    type: object
    required:
    - refresh
    properties:
      refresh:
        type: string
        description: ""
  data_5:
    type: object
    required:
    - email
    - password
    properties:
      email:
        type: string
        description: Users Email Address
      password:
        type: string
        description: Users Password
  data_7:
    type: object
    required:
    - confirm_password
    - email
    - full_name
    - password
    properties:
      full_name:
        type: string
        description: Full name of the User
      email:
        type: string
        description: User Email Address. Required in email format
      password:
        type: string
        description: User Password, must be at least 8characters
      confirm_password:
        type: string
        description: Re-enter password for confirmation
  data:
    type: object
    required:
    - city
    - country
    - state
    - street_address
    properties:
      street_address:
        type: string
        description: Users street address including house number
      city:
        type: string
        description: City or Town of Residence
      state:
        type: string
        description: State of Residence
      country:
        type: string
        description: Country of Residence
  data_2:
    type: object
    properties:
      street_address:
        type: string
        description: ""
      city:
        type: string
        description: ""
      state:
        type: string
        description: ""
      country:
        type: string
        description: ""
  data_1:
    type: object
    required:
    - city
    - country
    - state
    - street_address
    properties:
      street_address:
        type: string
        description: ""
      city:
        type: string
        description: ""
      state:
        type: string
        description: ""
      country:
        type: string
        description: ""
  data_4:
    type: object
    required:
    - amount
    properties:
      amount:
        type: number
        description: Deposit Amount
  data_3:
    type: object
    required:
    - amount
    properties:
      amount:
        type: number
        description: Withdrawal amount
      address:
        type: string
        description: Address to be associated with withdrawal.
